### ISSUE TITLE
(node:3735) UnhandledPromiseRejectionWarning: Error: Not supported with next.js webpack

### ISSUE THREAD

**Issue by Zemnmez** [wooorm/xdm#32]
Hey there!

Wrote a really quick plugin to make this work with webpack in next.js:
```javascript
const xdmPlugin = config => ({
    ...config,
    webpack(wpcfg, ...a) {
        wpcfg = {
            ...wpcfg,
            module: {
                ...wpcfg.module,
                rules: [
                    ...wpcfg.module.rules,
                    { test: /\.mdx$/, use: [{loader: 'xdm/webpack.cjs', options: {}}] }
                ]
            }
        }

        if (config.webpack) wpcfg = config.webpack(wpcfg, ...a);
        return wpcfg;
    }
})
```

This just merges in the rules as specified in the readme. However, when I run `yarn next dev`, I get:

```
(node:3735) UnhandledPromiseRejectionWarning: Error: Not supported
    at Object.module.exports (/mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/xdm/webpack.cjs:14:3)
    at LOADER_EXECUTION (/mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)  
    at provider (/mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9)
    at /mnt/c/Users/thoma/OneDrive/Documents/devel/linear/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

This corresponds to the `import()` line in webpack.cjs:
```javascript
'use strict'

/**
 * Webpack loader
 *
 * @remarks
 * To do: once webpack supports ESM loaders, remove this wrapper.
 *
 * @param {string} code
 */
module.exports = function (code) {
  var callback = this.async()
  // Note that `import()` caches, so this should be fast enough.
  import('./lib/integration/webpack.js').then((module) => // <- this line
    module.loader.call(this, code, callback)
  )
}
```

I'm not sure what this means, frankly

**Comment by lunelson** [comment]
As a guess —I'm not an expert— this may be because either your Node environment or Next.js are not supporting `import` syntaxes. Are you on Node >= 12? Otherwise, I can offer that in my other tests with xdm and Next.js (not the same use-case as yours), I had to use the [next-transpile-modules](https://github.com/martpie/next-transpile-modules) package [as I explained here](https://github.com/wooorm/xdm/issues/23#issuecomment-803283972)

**Comment by Zemnmez** [comment]
Ah, okay, my Node was just out of date. Thanks :)
