### ISSUE TITLE
How to make XDM handle type = 'html' MDAST nodes?

### ISSUE THREAD

**Issue by CyriacBr** [wooorm/xdm#90]
I have a need where I need to insert raw HTML as a MDAST Node. I cannot use a remark plugin for that, for complicated reasons.
However, XDM doesn't seem to be able to handle such a node directly, and I'm not really sure what to do.

Reproduction:
```ts
import { compile } from 'xdm';
import { Processor } from 'xdm/lib/core';
import { visit } from 'unist-util-visit';

const doc = `

## Quo non vix

Dissilit animo Pandione ardua situ quis ense, Triumphum matre. Mentita
pudibundaque quid: que mutantur fervoribus sunt ver negari.

<Test />
`;

async function main() {
  const compiled = await compile(doc, {
    jsx: true,
    remarkPlugins: [plugin],
  });
  console.log(String(compiled));
}

main();

function plugin(this: Processor) {
  return async function transform(tree: Node) {
    const promises: Promise<void>[] = [];

    visit(tree, (node: Node, index: number, parent: Node) => {
      if (node.name === 'Test') {
        node.type = 'html';
        node.value = '<span>Test</span>';
      }
    });

    await Promise.all(promises);
  };
}
```

This is the error I get: 
```
Error: Cannot handle unknown node `raw`
```
Full stack-trace:
```bash
/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:170880
  throw new Error("Cannot handle unknown node `" + node.type + "`");
        ^

Error: Cannot handle unknown node `raw`
    at Object.unknown2 (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:170880:9)
    at Object.one3 [as handle] (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:170813:17)
    at all3 (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:171122:28)
    at Object.root2 (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:171080:20)
    at Object.one3 [as handle] (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:170813:17)
    at toEstree (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:170856:24)
    at /media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:171220:20
    at wrapped (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:160343:16)
    at next (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:160319:23)
    at done (/media/[user]/0CC5166B0CC5166B/Work/docs-helper/out.js:160364:7)
```

Any help would be appreciated :pray:

**Comment by CyriacBr** [comment]
The reason I am doing this is for code-splitting. Since I partially hydrate my interactive JSX, I need them to have their separate bundle. If they are not exported, the whole compiled page needs to be loaded, which goes against my goal. By exporting them I can make several chunks for every JSX expressions I wish to hydrate, not just component, but complex JSX expressions that are not even imported.

> Perhaps this all, especially b), can be better done as a recma plugin even, which is given a JavaScript syntax tree, and can more easily look for certain JSX components everywhere, fetch some stuff for them, and then replace them?

I doubt this is needed by now but I'll keep that in mind, thanks. I will close the issue since it is resolved :).
